<?php
define('RESPONSE_SUCCESS_CODE',0);

define('RESPONSE_ERROR_HEADER',1);
define('RESPONSE_ERROR_PARAM_FAILS',5);
define('RESPONSE_ERROR_NETWORK',10000);
define('RESPONSE_ERROR_WITHOUT_LOGIN',10003);
define('RESPONSE_ERROR_MESSAGE_CODE_EXPIRED',10004);
define('RESPONSE_ERROR_MESSAGE_CODE_FAILS',10005);
define('RESPONSE_ERROR_BALANCE_NOT_ENOUGH',10006);
define('RESPONSE_ERROR_WITHOUT_USER',10007);
define('RESPONSE_ERROR_WITHOUT_BILL',10008);
define('RESPONSE_ERROR_UNKNOWN',10099);
define('RESPONSE_ERROR_BET_FAILS',10010);
define('RESPONSE_ERROR_TOO_OFTEN',10011);
define('RESPONSE_ERROR_DUPLICATE_DATA',1012);

define('RESPONSE_ERROR_MOBILE_FORMAT_FAILS',1010101);
define('RESPONSE_ERROR_OPERATORS_LIMIT',1010102);
define('RESPONSE_ERROR_MOBILE_OR_PASSWORD_FALIS',1010201);
define('RESPONSE_ERROR_USER_FORBIDDEN',1010202);
define('RESPONSE_ERROR_TEL_BE_REGISTER',1020304);

define('RESPONSE_ERROR_RECHARGE_MONRY_FAILS',1020201);
define('RESPONSE_ERROR_WITHOUT_RECHARGE_CHANNEL',1020202);
define('RESPONSE_ERROR_WITHOUT_TURE_NAME',1020203);
define('RESPONSE_ERROR_RECHARGE_NOT_EXIST',1020301);
define('RESPONSE_ERROR_RECHARGE_NOT_BELONG_TO_THIS_USER',1020302);

define('RESPONSE_ERROR_ISSUE_NOT_EXIST',1030101);


define('TIGER_LOTTERY_ID_OF_SSQ', 1); // 双色球
define('TIGER_LOTTERY_ID_OF_FC3D', 2); // 福彩3D
define('TIGER_LOTTERY_ID_OF_DLT', 3); // 超级大乐透
define('TIGER_LOTTERY_ID_OF_SD_11X5', 4); // 山东11选5
define('TIGER_LOTTERY_ID_OF_AH_11X5', 8); // 安徽11选5
define('TIGER_LOTTERY_ID_OF_HB_11X5', 18); // 湖北11选5

define('TIGER_LOTTERY_ID_OF_JL_K3', 5); // 吉林快三
define('TIGER_LOTTERY_ID_OF_JX_K3', 19); // 江西快三
define('TIGER_LOTTERY_ID_OF_JS_K3', 22); // 江苏快三

define('TIGER_LOTTERY_ID_OF_JZ', 6); // 竞彩足球
define('TIGER_LOTTERY_ID_OF_JZ_SPF', 601); // 足球胜平负
define('TIGER_LOTTERY_ID_OF_JZ_RQSPF', 602); // 足球让球胜平负
define('TIGER_LOTTERY_ID_OF_JZ_BF', 603); // 足球比分
define('TIGER_LOTTERY_ID_OF_JZ_ZJQ', 604); // 足球总进球
define('TIGER_LOTTERY_ID_OF_JZ_BQC', 605); // 足球半全场
define('TIGER_LOTTERY_ID_OF_JZ_HHTZ', 606); // 足球混合投注
define('TIGER_LOTTERY_ID_OF_JL', 7); // 竞彩篮球
define('TIGER_LOTTERY_ID_OF_JL_SF', 701); // 篮球胜负
define('TIGER_LOTTERY_ID_OF_JL_RFSF', 702); // 篮球让分胜负
define('TIGER_LOTTERY_ID_OF_JL_SFC', 703); // 篮球胜分差
define('TIGER_LOTTERY_ID_OF_JL_DXF', 704); // 篮球大小分
define('TIGER_LOTTERY_ID_OF_JL_HHTZ', 705); // 篮球混合投注

define('TIGER_LOTTERY_ID_OF_SFC_14', 20); // 胜负彩14场
define('TIGER_LOTTERY_ID_OF_SFC_9', 21); // 胜负彩任选九

define('TIGER_PLAY_ID_OF_NORMAL', 101); // 普通

define('PAYMENT_CHANNEL_ID_OF_LIANLIAN', 1); // 连连支付
define('PAYMENT_CHANNEL_ID_OF_ALIPAY', 2); // 支付宝
define('PAYMENT_CHANNEL_ID_OF_LIANLIANSDK', 5); // 连连支付SDK版
define('PAYMENT_CHANNEL_ID_OF_WEIXINGONGZHONG', 3); // 微信公众号支付
define('PAYMENT_CHANNEL_ID_OF_MANUAL', 6); // 手动转账页面
define('PAYMENT_CHANNEL_ID_OF_MANUAL_ALIPAY', 7); // 微信支付
define('PAYMENT_CHANNEL_ID_OF_HEEPAY', 9); // 汇付宝
define('PAYMENT_CHANNEL_ID_OF_YEEPAY', 11); // 易宝支付
define('PAYMENT_CHANNEL_ID_OF_ZWX', 12); //梓微兴支付
define('PAYMENT_CHANNEL_ID_OF_BAOFU', 10);//宝付银行卡支付
define('PAYMENT_CHANNEL_ID_OF_ZXWXH5', 13);//中信银行微信H5支付
define('PAYMENT_CHANNEL_ID_OF_ZXWXSDK', 14);//中信银行微信SDK支付
define('PAYMENT_CHANNEL_ID_OF_ZWXSDK', 15);//梓微兴微信SDK支付
define('PAYMENT_CHANNEL_ID_OF_XYWXSDK', 16);//兴业微信SDK支付

define('RECHARGE_URL_MD5_SALT', 'youcannotdoit');

define('COUPON_DATE_FOREVER', '2099-12-31 23:59:59'); // 永久红包有效期

define('BET_TICKET_NUMBER_LIMIT', 100); // 投注请求限制100票
define('BET_TICKET_AMOUNT_LIMIT', 20000); // 单票投注金额限制20000
define('BET_JC_TICKET_TIME_LIMIT', 99); // 竞彩单票投注倍数限制99
define('BET_SZC_TICKET_TIME_LIMIT', 50); // 福彩限制50倍

define('LOTTERY_PRICE', 2);
define('TICKET_STATUS_OF_UN_PRINTOUT', 0);
define('TICKET_STATUS_OF_PRINTOUTED', 1);
define('JC_PLAY_TYPE_SINGLE_STAGE', 51);
define('JC_PLAY_TYPE_MULTI_STAGE', 52);
define('ORDER_STATUS_OF_UNPAID', 0);

define('OS_OF_ANDROID', 1);
define('OS_OF_IOS', 2);

define('TIGER_PLAY_ID_OF_LEXUAN2', 34); // 乐选二（11选5 安徽支持，山东不支持）
define('TIGER_PLAY_ID_OF_LEXUAN3', 35); // 乐选三（11选5）
define('TIGER_PLAY_ID_OF_LEXUAN4', 36); // 乐选四（11选5）
define('TIGER_PLAY_ID_OF_LEXUAN5', 37); // 乐选五（11选5）

define('ORDER_TYPE_OF_NORMAL', 0);
define('ORDER_TYPE_OF_FOLLOW', 1);
define('ORDER_TYPE_OF_OPTIMIZE', 2);
