<?php
return array(
    'RESPONSE_MESSAGE' => array(
        RESPONSE_ERROR_PARAM_FAILS => '参数错误',
        RESPONSE_ERROR_NETWORK => '网络异常，请检查网络连接',
        RESPONSE_ERROR_WITHOUT_LOGIN => '用户还未登录或token已过期',
        RESPONSE_ERROR_MESSAGE_CODE_EXPIRED => '短信验证码过期',
        RESPONSE_ERROR_MESSAGE_CODE_FAILS => '短信验证码错误',
        RESPONSE_ERROR_BALANCE_NOT_ENOUGH => '余额不足',
        RESPONSE_ERROR_WITHOUT_USER => '用户不存在',
        RESPONSE_ERROR_WITHOUT_BILL => '订单不存在或已过期',
        RESPONSE_ERROR_TEL_BE_REGISTER => '电话号码已经注册',
        RESPONSE_ERROR_UNKNOWN => '未知错误',
        RESPONSE_ERROR_MOBILE_FORMAT_FAILS => '电话号码错误',
        RESPONSE_ERROR_OPERATORS_LIMIT => '运营商限制，发送失败',
        RESPONSE_ERROR_MOBILE_OR_PASSWORD_FALIS => '电话或密码错误',
        RESPONSE_ERROR_USER_FORBIDDEN => '用户被禁用',
        RESPONSE_ERROR_RECHARGE_MONRY_FAILS => '充值金额有错（格式检查和额度限制）',
        RESPONSE_ERROR_WITHOUT_RECHARGE_CHANNEL => '充值渠道不存在或者停用',
        RESPONSE_ERROR_WITHOUT_TURE_NAME => '没有实名认证',
        RESPONSE_ERROR_RECHARGE_NOT_EXIST => '充值订单不存在',
        RESPONSE_ERROR_RECHARGE_NOT_BELONG_TO_THIS_USER => '充值订单不属于此用户',
        RESPONSE_ERROR_BET_FAILS => '投注失败,请检查投注参数是否有误',
        RESPONSE_ERROR_TOO_OFTEN => '提交数据太频繁',
        RESPONSE_ERROR_DUPLICATE_DATA => '请勿重复提交数据',
        RESPONSE_ERROR_HEADER => '数据包头错误',
        RESPONSE_ERROR_ISSUE_NOT_EXIST => '彩期信息不存在',
    ),
);
