<?php
return array(
		'LOTTERY_CATEGORY' => array(
				'FULI' => array(
						TIGER_LOTTERY_ID_OF_SSQ,
						TIGER_LOTTERY_ID_OF_FC3D,
						TIGER_LOTTERY_ID_OF_JL_K3,
						TIGER_LOTTERY_ID_OF_SD_11X5,
						TIGER_LOTTERY_ID_OF_JX_K3,
                        			TIGER_LOTTERY_ID_OF_JS_K3,
				),
				'TIYU' => array(
						TIGER_LOTTERY_ID_OF_DLT,
						TIGER_LOTTERY_ID_OF_HB_11X5,
						TIGER_LOTTERY_ID_OF_AH_11X5,
						TIGER_LOTTERY_ID_OF_SD_11X5,
						TIGER_LOTTERY_ID_OF_JZ,
						TIGER_LOTTERY_ID_OF_JZ_SPF,
						TIGER_LOTTERY_ID_OF_JZ_RQSPF,
						TIGER_LOTTERY_ID_OF_JZ_BF,
						TIGER_LOTTERY_ID_OF_JZ_ZJQ,
						TIGER_LOTTERY_ID_OF_JZ_BQC,
						TIGER_LOTTERY_ID_OF_JZ_HHTZ,
						TIGER_LOTTERY_ID_OF_JL,
						TIGER_LOTTERY_ID_OF_JL_SF,
						TIGER_LOTTERY_ID_OF_JL_RFSF,
						TIGER_LOTTERY_ID_OF_JL_SFC,
						TIGER_LOTTERY_ID_OF_JL_DXF,
						TIGER_LOTTERY_ID_OF_JL_HHTZ,
						TIGER_LOTTERY_ID_OF_SFC_14,
						TIGER_LOTTERY_ID_OF_SFC_9 
				),
				'SZC' => array(
					TIGER_LOTTERY_ID_OF_SSQ,
					TIGER_LOTTERY_ID_OF_DLT,
					TIGER_LOTTERY_ID_OF_SD_11X5,
					TIGER_LOTTERY_ID_OF_HB_11X5,
					TIGER_LOTTERY_ID_OF_AH_11X5,
				),				
		) 
);

